#pragma once

inline const char* gDemoNodeTrees[][2] =
{
    { "Simple Terrain", "EQACAAAAAAAgQBAAAAAAQBkAEwDD9Sg/DQAEAAAAAAAgQAkAAGZmJj8AAAAAPwEEAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM3MTD4AMzMzPwAAAAA/" },
    { "Cellular Caves", "EwCamZk+GgABEQACAAAAAADgQBAAAACIQR8AFgABAAAACwADAAAAAgAAAAMAAAAEAAAAAAAAAD8BFAD//wAAAAAAAD8AAAAAPwAAAAA/AAAAAD8BFwAAAIC/AACAPz0KF0BSuB5AEwAAAKBABgAAj8J1PACamZk+AAAAAAAA4XoUPw==" },
    { "cave gen", "EAAK16M/IAARAAMAAADNzAxAEAAAACBAEwAAAIA/JQAAAIA/AAAAQAAAgD8AAIA/FwAAAIC/AACAPwAAgMAAAIA/BgAAuB6FPgAAAAA/AAAAAAABEACkcL0+EwCuR+G+JQAAAIA/j8LFQAAAgD8AAIA/IAAgABcAAACAvwAAgD8AAIC/mpkZPxYAAAAAABQAGgABCwABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAIA/AQsAAQAAAAIAAAAAAAAAAAAAAAEXAAAAgL8AAIA/AAAAAM3MzL4GAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAABFAD//w4AAArXozwACtejPAAK16O8AAAAAAAAuB6FPwEUAP//DgAACtejPAAK16O8AArXo7wAAAAAAAAAAIA/AAAAgD4AAACAPwAfhas+" },
    { "city mask", "EwAK1yM+EwAzMzM/EQADAAAAAACAQBAAAACAPxsAHQAiABSuxz8K16M8FwAAAIC/AACAPwAAAAAAAIA/BwAAzczMPQAAACBBADMzMz8Aj8L1PgA9Ctc+"},
    { "biome value", "EgADAAAAAABAQBAAAAAAQAoAAQAAAAAAAAAAAACAPwAfhes+AAAAAD8AAAAAAA=="},
    { "topology mask", "EwAK1yM+HQASAAMAAAAAAEBAEAAAAABAHgAdABcAAAAAAAAAgD8K1yO89ijcPyMAAQsAAQAAAAEAAAAAAAAAAgAAAAAAAIA/ANejsD8AAACAPwAAAAAAAB+F6z4AAAAAPwAAAAAAARMAMzMzPxEAAwAAAAAAgEAQAAAAgD8bAB0AIgAUrsc/CtejPBcAAACAvwAAgD8AAAAAAACAPwcAAM3MzD0AAAAgQQAzMzM/AI/C9T4APQrXPg==" },
    { "base topology", "GQAEAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ0AAwAAAKRwPUAlAM3MzD0AAAA/zczMPQAAgD8pAAAAAAA/ARcAAACAvwAAAD8AAAAAAACAPwYA" },
    { "dune topology", "HQAXAAAAgL8AAIA/mpmZPgAAAAATAAAAAD8lAAAAgD/hetQ/AACAPwAAgD8PAAIAAAAAAAA/CQAAKVwPPwBcjwJAAREAAwAAAI/CtT8QAOxROD8ZAB4AFwAAAIC/AACAPwAAgL8AAIBABgAAAAAAAAH//wYAAM3MzD8AzcxMPwAK1yM9" },
    { "mountain topology", "EAAAAEBBEwCPwvU9DwADAAAAAAAgQCkAABSuRz8AhetRQAAK16M8" },
    { "ravine topology", "EAAAACBBHwALAAEAAAAAAAAAAQAAAAIAAAAAAACAPwEXAAAAgL8AAIA/rkdhv4/C9T0QAArXoz8GAAB7FC4/AAAAAD8ACtcjPQ==" },
    { "cliff topology", "EQAEAAAAKVwPQBAAAAAAQBkAJwABAAAAGwAiAGZmZj8AAAAAFwAAAIC/AACAPwAAAAAAAIA/FgABAAAABgAAj8L1PQEXAAAAgL8AAIA/AAAAAJqZmT4OAAMAAAAAAAA/EwAUroc/KQAAAAAAvwAAAAAAARcAAACAvwAAgD8AAAAAzczMP///AAAAuB4FPwDNzEw/AJqZGT8=" },
    { "stalagmites", "HwATAAAAcEElAAAAgD8Xt9E4AACAPwAAgD8XAAAAgL8AAIA/AACAvwAAgEAHAAAAAAAAAAAAgD8=" },
    { "crystals", "EwCkcD1AGwAiAD0K174AAAAAGQAXAAAAgL8AAIA/AACAvx+Faz8LAAEAAAACAAAAAAAAAAIAAAAAAABAPwA9Cpe/AArXoz0=" },
    { "shelfs", "GwAiAM3MTD4AAAAAGQATAI/C9TwlAAAAekMAgDtFAAB6QwAAgD8XAAAAgL8AAIA/AAAAAAAAQEAHAACF61HAAArXozw=" },
    { "creaters", "HwATAK5H4T8XAAAAAAAAAIA/CtcjvHsU7j8eACAAGQALAAAAAAAAAAAAAQAAAAAAAAAAAACAPwB7FC6/Af//AQABFwAAAIC/AACAPwAAAAAAAABABgABGwD//wQAAAAAgL8ACtejPQAAAIA/" },
    { "mantle", "EwBvEoM6FwAAAIC/AACAPwAA+MMAAIBBIQAXAAAAgL8AAIA/AAAAAM3MzD0WAAIAAAAGABsAFwAAAIC/AACAPwAAAAAAAIA/DwACAAAAAAAAABMAAACAPxYAAQAAAAcAAAAAAAAAAAAAAAAAAABAASQAEAAAABcAAACAvwAAgD8AAAAAAACAPwYA" },
    { "flatlands", "AAAAAAAA" }
};
